name: Publish resumes
on: [push]
jobs:
  publish-resumes:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Build docker image...
        run: |
          docker build --tag rohannng/texlive .
      - name: Generate resumes...
        run: |
          docker run \
          --volume $(pwd):/data \
          rohannng/texlive \
          make
      - name: Generated resume pdf files.
        run: |
          ls -ltr ${{ github.workspace }}/*pdf
      - run: echo "ğŸ This job's status is ${{ job.status }}."