name: Publish resumes
on: [push]
jobs:
  publish-resumes:
    runs-on: ubuntu-latest
    container:
      image: rohannng/texlive-full:main
#      volumes:
#        - ${{ github.workspace }}:/data
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Generate resumes...
        run: |
          make
      - name: Generated resume pdf files.
        run: |
          ls -ltr ${{ github.workspace }} |
          ls -ltr /data
      - run: echo "ğŸ This job's status is ${{ job.status }}."